### ISSUE TITLE
React Carousel forces sliding animation when using `defaultIndex`

### ISSUE THREAD

**Issue by itsJimmyQ** [chakra-ui/ark#3043]
### Description

When I use `defaultIndex` prop, I expect the carousel to be rendered with that slide initially.
But instead, it would render the first image then slide through all the slides inbetween with a slide animation to the chosen default image.

### Link to Reproduction (or Detailed Explanation)

See steps.

### Steps to Reproduce

1. Implement a basic Ark UI carousel (Reect)
2. Have more than 1 image
3. Set prop `defaultIndex` to be larger than `0`

### Ark UI Version

4.4.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@itsJimmyQ 

Thanks for reaching out. Good catch. Will see what we can do :)

**Comment by itsJimmyQ** [comment]
Hey @cschroeter 
Is there any update on this bug?

**Comment by segunadebayo** [comment]
This has been fixed in a recent PR. We’ll publish a new version shortly.

**Comment by itsJimmyQ** [comment]
Awesome, thanks!

**Comment by itsJimmyQ** [comment]
Hi @segunadebayo 
I've updated to the latest version 4.8.0 the exact same issue still persists.

**Comment by itsJimmyQ** [comment]
Hey @cschroeter 
Thanks for the given update, however after upgrading to the latest version, I see some small API changes to the component but the mentioned issue still persists. Can you please double check and reopen this issue if needed?
